---
title: "Untitled"
author: "Gabe Mednick"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(shiny)
library(shinydashboard)
library(usmap)
library(ggrepel)
library(plotly)
library(viridis)
library(shinythemes)
theme_set(theme_light())
scale_colour_discrete <- scale_colour_viridis_d
```

```{r}
url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"
data <- c(
  "time_series_covid19_confirmed_global.csv",
  "time_series_covid19_deaths_global.csv",
  "time_series_covid19_confirmed_US.csv",
  "time_series_covid19_deaths_US.csv"
)
urls <- str_c(url, data)
```


```{r}
us_confirmed <- read_csv(urls[3]) %>%
  pivot_longer(cols = -(UID:Combined_Key), names_to = "date", values_to = "cases") %>%
  select(Admin2:cases) %>%
  janitor::clean_names() %>%
  mutate(date = mdy(date))
us_deaths <- read_csv(urls[4]) %>%
  pivot_longer(cols = -(UID:Population), names_to = "date", values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  janitor::clean_names() %>%
  mutate(date = mdy(date))

us_data <- us_deaths %>%
  select(deaths, date, combined_key, population) %>%
  left_join(us_confirmed, by = c("date", "combined_key")) %>%
  select(date, state = province_state, county = admin2, cases, deaths, population, lon = long, lat) %>%
  filter(!state %in% c("Diamond Princess", "Grand Princess"))

# get population data
uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

uid <- read_csv(uid_lookup_url) %>%
    filter(Country_Region == 'US') %>% 
  select(c(Province_State, Admin2, fips = FIPS))

```


```{r}
us_state <- us_data %>%
  group_by(state, date) %>%
  summarize(
    cases = sum(cases),
    deaths = sum(deaths),
    population = sum(population)
  ) %>%
  ungroup()

us_totals <- us_state %>%
  group_by(state) %>%
  summarize(
    cases = max(cases),
    deaths = max(deaths),
    population = max(population)
  ) %>%
  filter(cases > 0) %>%
  mutate(
    deaths_per_1e6 = 1000000 * (deaths / population),
    cases_per_1e6 = 1000000 * (cases / population)
  ) %>%
  filter(!is.na(deaths_per_1e6)) %>%
  arrange(desc(cases))
```


```{r}
county_filter <- tibble(unique(usmap::us_map(regions = "counties")$county)) %>%
    select(county = `unique(usmap::us_map(regions = "counties")$county)`) %>% 
    mutate(county = str_remove_all(county, " County"))


us_counties <- us_data %>%
  group_by(county, state, date) %>%
  summarize(
    cases = sum(cases),
    deaths = sum(deaths),
    population = sum(population)
  ) %>%
  ungroup() %>% 
    group_by(county, state) %>% 
  summarize(
    cases = max(cases),
    deaths = max(deaths),
    population = max(population)
  ) %>%
    ungroup() %>% 
  filter(cases > 0,
         county %in% county_filter$county) %>%
  mutate(
    deaths_per_1e6 = 1000000 * (deaths / population),
    cases_per_1e6 = 1000000 * (cases / population)
  ) %>%
  filter(!is.na(deaths_per_1e6)) %>%
  arrange(desc(cases))
us_counties <- us_counties %>% 
    left_join(uid, by = c('state' = 'Province_State', 'county' = 'Admin2')) 
#    mutate(county = str_c(county, " County"))
```

```{r}
us_total_sums <- us_data %>%
  group_by(date) %>%
  summarize(
    total_cases = sum(cases),
    total_deaths = sum(deaths)
  )

 daily_summary <- us_data %>%
      group_by(state, date) %>%
      summarise(
        cases_n = sum(cases),
        deaths_n = sum(deaths)
      ) %>%
      mutate(
        new_cases_n = cases_n - lag(cases_n, default = 0),
        new_deaths_n = deaths_n - lag(deaths_n, default = 0)
      ) %>%
      ungroup() %>%
      group_by(state) %>% 
      slice(which.max(date)) %>% 
      summarise(total_new_cases = sum(new_cases_n),
                total_new_death = sum(new_deaths_n)) %>% 
      ungroup() 
```


```{r}
# Cases per million per State map
cbs <- plot_usmap(
  data = us_totals,
  values = "cases_per_1e6",
  color = "black",
  labels = FALSE
) +
  ggplot2::aes(text = paste0(
    "State: ", state,
    "\nPopulation: ", format(population, big.mark = ","),
    "\nTotal cases: ", format(cases, big.mark = ","),
    "\nCases per mill: ", format(round(cases_per_1e6, 0), big.mark = ",")
  )) +
  scale_fill_viridis_c(
    name = "Cases per million",
    alpha = 0.5
  ) +
  theme(panel.background = element_rect(color = "grey80", fill = "grey80")) +
  theme(legend.position = "right", plot.title = element_text(face = "bold", size = 18, color = "#367588")) +
  labs(title = paste0("Total Cases in the USA: ", formatC(max(us_total_sums$total_cases), format = "d", big.mark = ",")),
       subtitle = "Cases per Million by State")
```


```{r}
# Deaths per million per State map

dbs <- plot_usmap(
  data = us_totals,
  values = "deaths_per_1e6",
  color = "black",
  labels = FALSE
) +
  ggplot2::aes(text = paste0(
    "State: ", state,
    "\nPopulation: ", format(population, big.mark = ","),
    "\nTotal deaths: ", format(deaths, big.mark = ","),
    "\nDeaths per mill: ", format(round(deaths_per_1e6, 0), big.mark = ",")
  )) +
  scale_fill_viridis_c(
    name = "Deaths per million",
    alpha = 0.5
  ) +
  theme(panel.background = element_rect(color = "grey80", fill = "grey80")) +
  theme(legend.position = "right", plot.title = element_text(face = "bold", size = 18, color = "#367588")) +
  labs(title = paste0("Total Deaths in the USA: ", formatC(max(us_total_sums$total_deaths), format = "d", big.mark = ",")),
       subtitle = "Deaths per Million by State")
```

```{r}
# Cases per million by county
states <- plot_usmap("states", 
                     color = "red",
                     fill = alpha(0.01))

county_map <- plot_usmap(
  data = us_counties,
  values = "cases_per_1e6",
  color = "black",
  size = 0.1) +
  ggplot2::aes(text = paste0(
    "State: ", county,
    "\nPopulation: ", format(population, big.mark = ","),
    "\nTotal cases: ", format(cases, big.mark = ","),
    "\nCases per mill: ", format(round(cases_per_1e6, 0), big.mark = ",")
  )) +
  scale_fill_viridis_c(
    name = "Cases per million",
    alpha = 0.5
  ) +
  theme(panel.background = element_rect(color = "black", fill = "grey80")) +
  theme(legend.position = "right", plot.title = element_text(face = "bold", size = 18, color = "#367588")) +
  labs(title = paste0("Cases by County"))
```

```{r}
#Example data (poverty rates)
county_data<-read.csv("https://www.ers.usda.gov/webdocs/DataFiles/48747/PovertyEstimates.csv?v=2529") %>% #
  filter(Area_name != "United States") %>%
  select(FIPStxt, Stabr, Area_name, PCTPOVALL_2018) %>%
  rename(fips = FIPStxt)

states <- plot_usmap("states", 
                     color = "red",
                     fill = alpha(0.01)) #this parameter is necessary to get counties to show on top of states
counties <- plot_usmap(data = county_data, 
                       values = "PCTPOVALL_2018",
                       color = "black",
                       size = 0.1)
```

#------------------------------------------------------------
Dashboard layout
```{r}
ui <- fluidPage(
  titlePanel("US COVID-19 Tracker"),
  theme = shinytheme("darkly"),
   sidebarLayout(
   sidebarPanel(
      selectInput("state", 
                label = "State:",
                choices = unique(us_data$state), 
                selected = c('California', 'Hawaii', 'Florida'),
                selectize = TRUE,
                multiple = TRUE),
    tabItem(tabName = "covid",
            imageOutput("picture", height='auto'))
    ),
  mainPanel(
   fluidRow(valueBoxOutput("caseCnt"),
    valueBoxOutput("deathCnt")),  
    tabsetPanel(type = 'tabs',
      tabPanel("Cases per Day",
        plotOutput("cases")), 
      tabPanel("Deaths per Day",
 plotOutput("deaths")),
 tabPanel("US Cases",
 plotlyOutput("caseMap")),
 tabPanel("US Deaths",
 plotlyOutput("deathsMap")),
 tabPanel("County level map",
 plotlyOutput("county")
      ))
)))
```


```{r}
server <- function(input, output) {
  # sidebar
  output$picture <- renderImage(
    {
      return(list(src = "covid.jpg", contentType = "image/jpg", alt = "covid", height = 195))
    },
    deleteFile = FALSE
  ) # src specifies path to jpg
  output$caseCnt <- renderValueBox({
    valueBox(
      value = prettyNum(sum(daily_summary$total_new_cases), big.mark = ","),
      subtitle = paste0("US Cases: ", as.character(max(us_total_sums$date)))
      
    )
  })
  output$deathCnt <- renderValueBox({
    valueBox(
      value = prettyNum(sum(daily_summary$total_new_death), big.mark = ","),
      subtitle = paste0("US Deaths: ", as.character(max(us_total_sums$date)))
    )
  })
  #------- dashboard body ------------

  # Line plot of cases vs time by State
  output$cases <- renderPlot({
    us_data %>%
      group_by(state, date) %>%
      summarise(
        cases_n = sum(cases),
        deaths_n = sum(deaths)
      ) %>%
      mutate(
        new_cases_n = cases_n - lag(cases_n, default = 0),
        new_deaths_n = deaths_n - lag(deaths_n, default = 0)
      ) %>%
      ungroup() %>%
      filter(state %in% input$state) %>%
      ggplot(aes(x = date, y = new_cases_n, color = state)) +
      geom_line(size = 1, alpha = 0.5) +
      theme(plot.title = element_text(hjust = 0.5, face = "bold", color = "#367588", size = 18)) +
      labs(
        title = "Cases per Day",
        subtitle = paste0("latest data from: ", as.character(max(us_total_sums$date))),
        y = "Cases",
        x = "Date",
        color = "State"
      ) +
      theme(panel.background = element_rect(color = "grey80", fill = "grey80")) +
      geom_text_repel(
        data = . %>%
          arrange(desc(date)) %>%
          group_by(state) %>%
          slice(1),
        aes(label = new_cases_n),
        position = position_nudge(8), hjust = -5, show.legend = FALSE
      )
  })

  # Cases per million by State map
  output$caseMap <- renderPlotly({
    ggplotly(cbs,
      tooltip = "text"
    ) %>%
      config(displayModeBar = FALSE)
  })

  # Line plot of deaths vs time by State
  output$deaths <- renderPlot({
    us_data %>%
      group_by(state, date) %>%
      summarise(
        cases_n = sum(cases),
        deaths_n = sum(deaths)
      ) %>%
      mutate(
        new_cases_n = cases_n - lag(cases_n, default = 0),
        new_deaths_n = deaths_n - lag(deaths_n, default = 0)
      ) %>%
      ungroup() %>%
      filter(state %in% input$state) %>%
      ggplot(aes(x = date, y = new_deaths_n, color = state)) +
      geom_line(size = 1, alpha = 0.5) +
      theme(plot.title = element_text(hjust = 0.5, face = "bold", color = "#367588", size = 18)) +
      theme(panel.background = element_rect(color = "grey80", fill = "grey80")) +
      labs(
        title = "Deaths per Day",
        subtitle = paste0("latest data from: ", as.character(max(us_total_sums$date))),
        y = "Deaths",
        x = "Date",
        color = "State"
      ) + 
      geom_text_repel(
        data = . %>%
          arrange(desc(date)) %>%
          group_by(state) %>%
          slice(1),
        aes(label = new_deaths_n),
        position = position_nudge(8),
        hjust = -5, show.legend = FALSE
      )
  })

  # Deaths per million by State map
  output$deathsMap <- renderPlotly({
    ggplotly(dbs,
      tooltip = "text"
    ) %>%
      config(displayModeBar = FALSE)
  })
  
   # Cases per million by county
  output$county <- renderPlotly({
    ggplotly(county_map,
      tooltip = "text"
    ) %>%
      config(displayModeBar = FALSE)
  })
}

shinyApp(ui = ui, server = server)
```
